name: Auto Assign

on:
  pull_request_target:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  use-auto-assign:
    uses: JackTestHook/.github/.github/workflows/auto-assign.yaml@main