name: "[Issue Management] Link Backport PR Issue"

on:
  pull_request_target:
    types: [ opened ]
    branches:
    - master
    - "v*"

jobs:
  check-backport:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check if PR is a backport
      run: |
        if [[ "$(echo "${{ github.event.pull_request.title }}" | sed 's/"/\\"/g')" =~ "backport #" ]]; then
          echo "BACKPORT=true" >> $GITHUB_ENV
        else
          echo "BACKPORT=false" >> $GITHUB_ENV
        fi

    - name: Extract backport branch and issue number
      if: env.BACKPORT == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      run: |
        # Extract branch from the target branch of the PR
        BRANCH=$(echo "${{ github.event.pull_request.base.ref }}")
        BRANCH=$(echo "${BRANCH}" | sed 's/\./\\./g')   # Escape periods
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

        # Extract issue numbers from PR body (support both formats)
        BODY="${{ github.event.pull_request.body }}"
        ISSUE_NUMBERS=$(echo "$BODY" | grep -oE 'JackTestHook/test#([0-9]+)' | cut -d'#' -f2)
        ISSUE_NUMBERS_URL=$(echo "$BODY" | grep -oE 'https://github.com/JackTestHook/test/issues/[0-9]+' | awk -F'/' '{print $NF}')
        ALL_ISSUES=$(echo -e "$ISSUE_NUMBERS\n$ISSUE_NUMBERS_URL" | grep -E '^[0-9]+$' | sort -u)
        
        ORIGINAL_ISSUE_NUMBER=$(echo $ALL_ISSUES | xargs) # trim
        echo "ORIGINAL_ISSUE_NUMBER=$ORIGINAL_ISSUE_NUMBER" >> $GITHUB_ENV

    - name: Link the PR with the backport issue
      if: ${{ env.BACKPORT == 'true' && env.ORIGINAL_ISSUE_NUMBER != '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      run: |
        for issue_number in "${{ env.ORIGINAL_ISSUE_NUMBER }}"; do
          echo "Found source issue JackTestHook/test#${issue_number}"
          issue_title=$(gh issue view "$issue_number" --repo JackTestHook/test --json title --jq ".title")

          if [[ -n "$issue_number" && -n "$issue_title" ]]; then
            search_title="[backport ${BRANCH}] ${issue_title}"
            backport_issue_number=$(
              gh issue list --repo JackTestHook/test --state open --search '"${search_title}"' --json number --jq ".[].number"
            )

            if [[ -n "$backport_issue_number" ]]; then
              echo "Found backport issue JackTestHook/test#${backport_issue_number}"
              echo "Linking backport issue JackTestHook/test#${backport_issue_number}"
              gh issue comment --repo JackTestHook/test "${backport_issue_number}" --body "Backport PR: ${{ github.event.pull_request.html_url }}"
              continue
            fi
          fi

          echo "No issue title found"
        done