name: "[Issue Management] Add Issues to Projects"
on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
        default: ""
  issues:
    types: [opened]

env:
  HARVESTER_PROJECT_URL: https://github.com/orgs/JackTestHook/projects/1
  COMMUNITY_PROJECT_URL: https://github.com/orgs/JackTestHook/projects/2

jobs:
  suse-org:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Is SUSE Member
      id: is-suse-member
      uses: rancher/gh-issue-mgr/get-user-teams-membership@main
      with:
        username: ${{ inputs.name }}
        organization: SUSE
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
    
    - name: Is Harvester Member
      id: is-harvester-member
      uses: rancher/gh-issue-mgr/get-user-teams-membership@main
      with:
        username: ${{ inputs.name }}
        organization: harvester
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
    
    - name: echo
      run: |
        echo "steps.is-harvester-member.outputs.teams: ${{ steps.is-harvester-member.outputs.teams }}"
        echo "steps.is-suse-member.outputs.teams: ${{ steps.is-suse-member.outputs.teams }}"
        echo "fromJSON(steps.is-harvester-member.outputs.teams)[0]: ${{ fromJSON(steps.is-harvester-member.outputs.teams)[0] }}"
        echo "fromJSON(steps.is-suse-member.outputs.teams)[0]: ${{ fromJSON(steps.is-suse-member.outputs.teams)[0] }}"
        echo "fromJSON(steps.is-harvester-member.outputs.teams)[0] == null: ${{ fromJSON(steps.is-harvester-member.outputs.teams)[0] == null }}"
        echo "fromJSON(steps.is-suse-member.outputs.teams)[0] != null: ${{ fromJSON(steps.is-suse-member.outputs.teams)[0] != null }}"
    
    - name: test isTeamMember 1
      if : ${{steps.is-harvester-member.outputs.isTeamMember == 'true'}}
      run: |
        echo "test isTeamMember 1"

    - name: test isTeamMember 2 
      if : ${{steps.is-harvester-member.outputs.isTeamMember == true }}
      run: |
        echo "test isTeamMember 2"

    - name: test isTeamMember 3
      if : ${{steps.is-harvester-member.outputs.isTeamMember == 'false'}}
      run: |
        echo "test isTeamMember 3"

    - name: test isTeamMember 4
      if : ${{steps.is-harvester-member.outputs.isTeamMember == false}}
      run: |
        echo "test isTeamMember 4"

    - name: test isTeamMember 5
      if : |
        steps.is-harvester-member.outputs.isTeamMember == 'false'
      run: |
        echo "test isTeamMember 5"
    
    - name: test isTeamMember 6
      if : |
        steps.is-harvester-member.outputs.isTeamMember == false
      run: |
        echo "test isTeamMember 6"

    - name: test condition
      if: ${{
        fromJSON(steps.is-suse-member.outputs.teams)[0] != null &&
        fromJSON(steps.is-harvester-member.outputs.teams)[0] == null
        }}
      run: |
        echo "This is a test condition that should run only if the user is a SUSE member and not a Harvester member."
  # harvester:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v4
      
  #   - name: Is Harvester Member
  #     id: is-harvester-member
  #     uses: rancher/gh-issue-mgr/get-user-teams-membership@main
  #     with:
  #       username: ${{ github.event.issue.user.login }}
  #       organization: harvester
  #       GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

  #   - name: Add Issue to Harvester Sprint Project
  #     if: fromJSON(steps.is-harvester-member.outputs.teams)[0] != null 
  #     uses: actions/add-to-project@v1.0.2
  #     with:
  #       project-url: ${{ env.HARVESTER_PROJECT_URL }}
  #       github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
  #       labeled: kind/test
  #       label-operator: NOT

  #   # - name: Assign Milestone to Issue
  #   #   if: ${{
  #   #     fromJSON(steps.is-harvester-member.outputs.teams)[0] != null &&
  #   #     github.event.issue.milestone == null
  #   #     }}
  #   #   env:
  #   #     GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
  #   #   run: |
  #   #     ISSUE_NUMBER="${{ github.event.issue.number }}"
  #   #     gh issue edit "$ISSUE_NUMBER" --milestone "Planning"
  
  # community:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Is Harvester Member
  #     id: is-harvester-member
  #     continue-on-error: true
  #     uses: rancher/gh-issue-mgr/get-user-teams-membership@main
  #     with:
  #       username: ${{ github.event.issue.user.login }}
  #       organization: harvester
  #       GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

  #   - name: Get Issue
  #     if: steps.is-harvester-member.outcome == 'success'
  #     uses: rancher/gh-issue-mgr/request-action@main
  #     id: issue
  #     with:
  #       route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

  #   - name: Add Issue to Community Sprint Project
  #     id: add-project
  #     if: |
  #       steps.is-harvester-member.outcome == 'success' &&
  #       fromJSON(steps.is-harvester-member.outputs.teams)[0] == null
  #     uses: actions/add-to-project@v1.0.2
  #     with:
  #       project-url: ${{ env.COMMUNITY_PROJECT_URL }}
  #       github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

  #   - name: Update Item To New
  #     if: |
  #       steps.is-harvester-member.outcome == 'success' &&
  #       fromJSON(steps.is-harvester-member.outputs.teams)[0] == null &&
  #       steps.add-project.outputs.itemId != ''
  #     uses: rancher/gh-issue-mgr/update-project-fields@main
  #     with:
  #       project-url: ${{ env.COMMUNITY_PROJECT_URL }}
  #       github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
  #       item-id: ${{ steps.add-project.outputs.itemId }}
  #       field-keys: Status,Sprint
  #       field-values: "New,[0]"

