name: Pull Request Preview

on:
  pull_request_target:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install netlify-cli -g yarn

      - name: Deploy to Netlify
        continue-on-error: true
        run: |
          DEBUG=* netlify deploy --debug --site "${{ secrets.NETLIFY_SITE_ID }}" --auth "${{ secrets.NETLIFY_AUTH_TOKEN }}" --message "Deploy from GitHub Action (pull-request: ${{ github.event.number }}, ${{ github.event.pull_request.head.sha }})" --dir ./build
      
      # - name: Check
      #   run: >
      #     cat deploy_output.json
          